<h1 align=center><font size=5>Python lists vs Numpy arrays</font></h1>

## Table of contents

- [Python lists](#lists)
- [Numpy arrays](#numpy)
- [List vs Numpy array](#listvsnumpy) 
- [Tuples](#tuple)

### Python lists <a id='lists'></a>

In [ ]:
mylist = [1, 2, 3, 4, 5]
mylist

input('what is your name')

what is your nameasfadsf


'asfadsf'

In [ ]:
mylist[0]

1

In [ ]:
mylist[4]
mylist[-1]

5

In [ ]:
mylist[-2]

4

In [ ]:
print(mylist[4])
print(mylist[-1])

5
5


In [ ]:
print(mylist[4], mylist[-1])

In [ ]:
mylist[2:4] #[2:4] -> [2:3]

[3, 4]

In [ ]:
mylist[:-1]

[1, 2, 3, 4]

In [ ]:
len(mylist)

5

In [ ]:
mylist.append(8)
mylist

[1, 2, 3, 4, 5, 8]

In [ ]:
mylist.append('Hi')
mylist

[1, 2, 3, 4, 5, 8, 'Hi']

In [ ]:
mylist.insert(2, 9) 
mylist

[1, 2, 9, 3, 4, 5, 8, 'Hi']

In [ ]:
mylist.remove('Hi')
mylist

[1, 2, 9, 3, 4, 5, 8]

In [ ]:
newlist = mylist.copy()
newlist

[1, 2, 9, 3, 4, 5, 8]

In [ ]:
aaaa = [1,2,3,4,5]
bbbb = aaaa
aaaa[2] = 'Hi'
print(bbbb)

[1, 2, 'Hi', 4, 5]


In [ ]:
newlist*2

[1, 2, 9, 3, 4, 5, 8, 1, 2, 9, 3, 4, 5, 8]

In [ ]:
mylist/3

TypeError: ignored

In [ ]:
mylist = [i/3 for i in mylist]
mylist

[0.3333333333333333,
 0.6666666666666666,
 3.0,
 1.0,
 1.3333333333333333,
 1.6666666666666667,
 2.6666666666666665]

In [ ]:
for i in range(len(mylist)):
    print(mylist[i]/3)

0.1111111111111111
0.2222222222222222
1.0
0.3333333333333333
0.4444444444444444
0.5555555555555556
0.8888888888888888


In [ ]:
list1 = [1, 2, 3]
list2 = [4, 5, 6]

list1 + list2

[1, 2, 3, 4, 5, 6]

In [ ]:
list3 = [x+y for x, y in zip(list1, list2)]
#list3 = [list1[i] + list2[i] for i in range(len(list1))]
list3

[5, 7, 9]

In [ ]:
list4 = [x+y for x in list1 for y in list2]
list4

[5, 6, 7, 6, 7, 8, 7, 8, 9]

In [ ]:
mylist = list(range(5))
print(mylist)

print(type(mylist))

[0, 1, 2, 3, 4]
<class 'list'>


In [ ]:
for i in mylist:
    print(i)

0
1
2
3
4


In [ ]:
for i in range(2, 5):
    print(i)

2
3
4


In [ ]:
list = ['a', 'b', 'c']

for idx, val in enumerate(list):
    print(idx, val)

0 a
1 b
2 c


In [ ]:
?enumerate

### Numpy arrays <a id = 'numpy'></a> 

In [ ]:
import numpy

In [ ]:
myarray = numpy.array([1, 2, 4])
myarray

array([1, 2, 4])

In [ ]:
import numpy as np

myarray = np.array([1, 2, 3])
myarray

array([1, 2, 3])

In [ ]:
myarray = np.array((1, 2, 3))
myarray

array([1, 2, 3])

In [ ]:
myarray = np.array(1, 2, 3)
myarray

ValueError: ignored

In [ ]:
myarray[0]

1

In [ ]:
myarray[2]
myarray[-1]

3

In [ ]:
myarray[1:]

array([2, 3])

In [ ]:
myarray = np.append(myarray, 6) 
myarray

array([1, 2, 3, 6])

In [ ]:
myarray/3

array([0.33333333, 0.66666667, 1.        , 2.        ])

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a.shape

(2, 3)

In [ ]:
a.size

6

In [ ]:
a.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
a.dtype

dtype('int64')

In [ ]:
type(a)

numpy.ndarray

In [ ]:
b = np.array([1, 2, 3.])
b

array([1., 2., 3.])

In [ ]:
b.dtype

dtype('float64')

In [ ]:
b = np.array([1, 2., 3 + 4j])
b.dtype

dtype('complex128')

In [ ]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [ ]:
np.arange(1, 5)

array([1, 2, 3, 4])

In [ ]:
np.arange(1, 5, 2)

array([1, 3])

In [ ]:
np.linspace(2, 5)

array([2.        , 2.06122449, 2.12244898, 2.18367347, 2.24489796,
       2.30612245, 2.36734694, 2.42857143, 2.48979592, 2.55102041,
       2.6122449 , 2.67346939, 2.73469388, 2.79591837, 2.85714286,
       2.91836735, 2.97959184, 3.04081633, 3.10204082, 3.16326531,
       3.2244898 , 3.28571429, 3.34693878, 3.40816327, 3.46938776,
       3.53061224, 3.59183673, 3.65306122, 3.71428571, 3.7755102 ,
       3.83673469, 3.89795918, 3.95918367, 4.02040816, 4.08163265,
       4.14285714, 4.20408163, 4.26530612, 4.32653061, 4.3877551 ,
       4.44897959, 4.51020408, 4.57142857, 4.63265306, 4.69387755,
       4.75510204, 4.81632653, 4.87755102, 4.93877551, 5.        ])

In [ ]:
np.linspace(2, 5, 3)

array([2. , 3.5, 5. ])

In [ ]:
np.logspace(2, 5, 3)

array([   100.        ,   3162.27766017, 100000.        ])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is

In [ ]:
help(np.random.rand)

Help on built-in function rand:

rand(...) method of numpy.random.mtrand.RandomState instance
    rand(d0, d1, ..., dn)
    
    Random values in a given shape.
    
    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `random_sample`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.
    
    Create an array of the given shape and populate it with
    random samples from a uniform distribution
    over ``[0, 1)``.
    
    Parameters
    ----------
    d0, d1, ..., dn : int, optional
        The dimensions of the returned array, must be non-negative.
        If no argument is given a single Python float is returned.
    
    Returns
    -------
    out : ndarray, shape ``(d0, d1, ..., dn)``
        Random values.
    
    See Also
    --------
    random
    
    Examples
    --------
    >>> np.random.rand(3,2)
    arra

In [ ]:
np.random.rand?

In [ ]:
np.random.randint?

In [ ]:
np.random.seed(1)
np.random.rand(3)

array([4.17022005e-01, 7.20324493e-01, 1.14374817e-04])

In [ ]:
a = np.random.randint(2, size = (2, 3))
a

array([[0, 0, 0],
       [1, 0, 0]])

In [ ]:
np.random.seed(14121)
a = np.random.randint(2, size = (2, 3))
a

array([[0, 1, 1],
       [0, 0, 0]])

### List vs Numpy array <a id = 'listvsnumpy'></a> 

1. NumPy is convenient to use
2. Numpy array consumes less memory than python list

In [ ]:
import sys

n = 10
mylist = range(n)

print("Size of list:", sys.getsizeof(1)*len(mylist))

Size of list: 280


In [ ]:
print(sys.getsizeof(1), sys.getsizeof(2))

28 28


In [ ]:
myarray = np.arange(n)

print("Size of NumPy array:", myarray.itemsize * myarray.size)

Size of NumPy array: 80


3. Numpy array is fast as compared to the python list

In [ ]:
import time

n = 100000000

list1 = range(n)
list2 = range(n)

start_time = time.time()
result = [(x+y) for x, y in zip(list1, list2)]
end_time = time.time()  

print("Time for python list in msec: ", (end_time - start_time)*1000)

Time for python list in msec:  14024.630069732666


In [ ]:
arr1 = np.arange(n)
arr2 = np.arange(n)

start_time = time.time()
result = arr1+arr2
end_time = time.time() 

print("Time for numPy array in msec:", (end_time - start_time)*1000)

Time for numPy array in msec: 1677.9053211212158


### Tuples <a id = 'tuple'></a>

In [ ]:
mytuple = (1, 2, 3)
mytuple

(1, 2, 3)

In [ ]:
tuple1 = (1, 2, 3)
tuple2 = ('hi', 'how are you')

tuple3 = tuple1 + tuple2
print(tuple3)

(1, 2, 3, 'hi', 'how are you')


In [ ]:
len(tuple3)

5

In [ ]:
# nested tuples
tuple3 = (tuple1, tuple2)
tuple3

((1, 2, 3), ('hi', 'how are you'))

In [ ]:
len(tuple3)

2

In [ ]:
len(tuple3[0])

3

In [ ]:
from google.colab import drive
drive.mount('/content/drive')